language: node_js
node_js: node
services: mongodb
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: RSkQPkwUW2hrIATtkXBv+RC58RLfm6eVdZTKVUvd/yGqM5EG/clce/jl7LbfRjyVkcdRhBDf0ObvnpqeSh7//ijNDcNZTLsuUBAxkTFqDtvUbbHvrctaRba9h6GtyWwCK+XbIBVH5kkHtqw9d1zyCRpqNJ5FN7aOxdYcuvnpBC3P3zGws5gyopi5ZMNcr8YHRx0NC6bkzqg9N7fmv9iyjOzCaeUPde8zk68O65yrAfEs9Dm0sgUrc8mP6SBXzO/scJsX40KfgaQNvRfdR5ImnWOyp39UeDI1jRSdjAQ7SF4ZLT05Qhnxo9t8EdZ3OTXndmSTDq9jL3t0ENFXa72LcPEbqpcGPiovP33nt+xn3vi/QtF2RRESYsGHnED4+siJCcjEmLonixo7qFUqDGnISwulHM8HsAE67Stg4k2lZRv6Nb2vuLlYgyfjwt8QYzkiZDLMj9daxpxvYYKn9Dp4v93WPe9INJAHipkNeyF43nmLvxPhWuQhTGHdKhzDGLjGrHsOZKIyguNUzL3uY8nYZyAzZClEZSkoLnAr66o/pV99vrC9ceTikBn9CpsMxUa1Pbhb24XhijJGlbaePdKrWtPEKq7P7Q4/sh+Y2uVH9ZRL6bRf/ZtKM8nEEcOh2Te1B99xxTKGFY4Uhxo9BnZN8Nms95rLYS6dfJ7LGID4W70=
  app: agile-sands-31281
  on:
    repo: maripal/treasurely-api
